### ISSUE TITLE
 Unable to load DLL 'iris.dll'

### ISSUE THREAD

**Issue by rhenrhee** [AgoraIO-Community/Agora-C_Sharp-SDK#2]
Hello! 
If you do everything according to the instructions, after installing the package, building and running the project causes an exception.

System.DllNotFoundException
  HResult=0x80131524
  Message = Unable to load DLL 'iris.dll' or one of its dependencies: The specified module was not found. (0x8007007E)

C:\Agora-C_Sharp-SDK\OneToOneVideo\OneToOneVideo\bin\Debug\netcoreapp3.1>dotnet OneToOneVideo.dll
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'iris.dll' or one of its dependencies: The specified module was not found. (0x8007007E)
   at agorartc.AgorartcNative.CreateIrisEngine()
   at agorartc.AgoraRtcEngine.CreateRtcEngine()
   at OneToOneVideo.OneToOneVideoDemo..ctor() in C:\Agora-C_Sharp-SDK\OneToOneVideo\OneToOneVideo\OneToOneVideoDemo.cs:line 27
   at OneToOneVideo.Program.Main() in C:\Agora-C_Sharp-SDK\OneToOneVideo\OneToOneVideo\Program.cs:line 20

27 string is that: "Rtc = AgoraRtcEngine.CreateRtcEngine();"

What is the problem and how can it be solved?

**Comment by YiqingJackieHuang** [comment]
Hi @rhenrhee! Please take a second read of the instructions : ) By following *STEP 4* in the instructions:

4. Find all DLL files showed in `Solution Explorer` and set the `Copy to Output Directory` property in `Properties->Advanced` to `Copy always`.
![STEP 4](https://user-images.githubusercontent.com/70505024/119075817-04f9c980-ba24-11eb-9f8b-dd4ff63814bf.png)

All the related dynamic libraries will be copied to the target directory when building.

**Comment by rhenrhee** [comment]
Yes, everything helped! Thank you!
