### ISSUE TITLE
iris.dll是什么

### ISSUE THREAD

**Issue by allenlooplee** [AgoraIO-Community/Agora-C_Sharp-SDK#3]
看到这个C# SDK通过P/Invoke调iris.dll，请问这个iris.dll是什么呢？

**Comment by YiqingJackieHuang** [comment]
`iris.dll` is a C Wrapper connecting our Native SDK and C# SDK.

**Comment by allenlooplee** [comment]
> `iris.dll` is a C Wrapper connecting our Native SDK and C# SDK.

Is it open source? If so, where can I find the source?

I noticed that this C# SDK is targeting netcoreapp3.1 and I wonder if it still works I re-target it to net48. iris.dll is a dependency so I want to know if it would block the way.

**Comment by YiqingJackieHuang** [comment]
> > `iris.dll` is a C Wrapper connecting our Native SDK and C# SDK.
> 
> Is it open source? If so, where can I find the source?
> 
> I noticed that this C# SDK is targeting netcoreapp3.1 and I wonder if it still works I re-target it to net48. iris.dll is a dependency so I want to know if it would block the way.

I am afraid not. However, in my point of view, your requirement on re-targeting the project to *net48* is only related to [this setting](https://github.com/AgoraIO-Community/Agora-C_Sharp-SDK/blob/7e34b529539328ddf9c3fcf225695d1bbe9ef671/agorartc/agorartc/agorartc.csproj#L4). By changing this setting and rebuilding a new target (*agorartc.dll*), it can support *net48*.

**Comment by allenlooplee** [comment]
OK. Thanks. I'm closing this issue and will try later.
